name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main # プルリクエストがメインブランチに送信されたとき

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout リポジトリ
        uses: actions/checkout@v3

      - name: インストール Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # 使用したいNode.jsのバージョンに設定

      - name: 依存関係のインストール
        run: npm install # もしくは yarn install

      - name: テスト実行
        run: echo "Test Success" # もしくはテストスクリプトを指定

      - name: マージ（テストが成功した場合）
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.sha }}
          git push origin main
